name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # Build Jekyll (to satisfy GitHub Pages expectations)
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site_jekyll
      
      # Build Angular app
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Angular app
        run: npm run build -- --base-href /
      
      # Copy Angular build to the root of the site
      - name: Copy Angular build to site root
        run: |
          rm -rf ./_site
          mkdir -p ./_site
          cp -R ./dist/alex1kariuki.github.io/browser/* ./_site/
          cp -R ./_site_jekyll/assets ./_site/assets || true
      
      # Add .nojekyll file to prevent GitHub Pages from running Jekyll again
      - name: Add .nojekyll file
        run: touch ./_site/.nojekyll
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 